export const pacientes = [
    {
        id: 1,
        nombre: "Mario",
        apellidos: "Cataluña",
        sexo: "Hombre",
        temperatura: 36.8,
        frecuenciaCardiaca: 80,
        especialidad: "Medico de familia",
        edad: 44,
    },
    {
        id: 2,
        nombre: "Estefania",
        apellidos: "Moreno",
        sexo: "Mujer",
        temperatura: 36.8,
        frecuenciaCardiaca: 70,
        especialidad: "Medico de familia",
        edad: 43,
    },
    {
        id: 3,
        nombre: "Jonathan",
        apellidos: "Heismann",
        sexo: "Hombre",
        temperatura: 36.8,
        frecuenciaCardiaca: 90,
        especialidad: "Pediatra",
        edad: 8,
    },
    {
        id: 4,
        nombre: "Maria",
        apellidos: "Pinta",
        sexo: "Mujer",
        temperatura: 36.8,
        frecuenciaCardiaca: 120,
        especialidad: "Medico de familia",
        edad: 20,
    },
    {
        id: 5,
        nombre: "Raul",
        apellidos: "Diaz",
        sexo: "Hombre",
        temperatura: 36.8,
        frecuenciaCardiaca: 110,
        especialidad: "Cardiólogo",
        edad: 30,
    },
    {
        id: 6,
        nombre: "Olga",
        apellidos: "Briales",
        sexo: "Mujer",
        temperatura: 39.8,
        frecuenciaCardiaca: 80,
        especialidad: "Pediatra",
        edad: 11,
    },
];